# Generated by Django 5.2.17 on 2026-08-18 13:36

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("created", "criou a tarefa"),
                            ("updated", "atualizou um campo"),
                            ("status_changed", "mudou o status"),
                            ("section_changed", "moveu de seção"),
                            ("assigned", "alterou o responsável"),
                            ("commented", "comentou"),
                            ("deleted", "excluiu a tarefa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field", models.CharField(blank=True, max_length=40)),
                (
                    "old_value",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["task", "-created_at"],
                        name="activities__task_id_5d0898_idx",
                    )
                ],
            },
        ),
    ]
